name: to_do_list_dev
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter  
  
  cupertino_icons: ^1.0.2

  
  intl: ^0.19.0
  equatable: ^2.0.5
  bloc: ^8.1.4
  mocktail: ^1.0.3
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.0.15
  flutter_bloc: ^8.1.5
  coverage: ^1.7.2
  
 


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1

  build_runner: ^2.4.6
  isar_generator: ^3.1.0+1

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/logo/logo.png"


flutter:
  uses-material-design: true

  fonts:
    - family: LTWave
      fonts:
        - asset: assets/fonts/LTWave-Bold.ttf
        - asset: assets/fonts/LTWave-Light.ttf
        - asset: assets/fonts/LTWave-Regular.ttf

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
